『main1.py』
テストデータ：log1.txt
出力結果：故障状態のサーバアドレス：10.20.30.1/16
        故障期間：0:01:00
        故障状態のサーバアドレス：10.20.30.1/16
        故障期間：0:10:00

『main2.py』
テストデータ：log2.txt
出力結果：故障状態のサーバアドレス：10.20.30.1/16
        故障期間：0:10:00

『main3.py』
テストデータ：log3.txt
出力結果：過負荷状態のサーバアドレス：10.20.30.1/16
        過負荷状態の期間：0:13:00
        過負荷状態のサーバアドレス：10.20.30.1/16
        過負荷状態の期間：0:12:00
        過負荷状態のサーバアドレス：10.20.30.1/16
        過負荷状態の期間：0:09:59